package ch.gradely.api.controller.error;

public enum ErrorType {
	INVALID_PASSWORD,
	VALUE_LOWER_OR_EQUAL_ZERO,
	INVALID_USERNAME,
	UNKNOWN_SCHOOL,
	UNKNOWN_COLUMN,
	INVALID_EMAIL,
	EMPTY_NAME,
	UNKNOWN_SUBJECT, UNKNOWN_SEMESTER, UNKNOWN_GRADE, VALUE_LOWER_ZERO, INVALID_GRADE_VALUE, SQL_ERROR
}
